### ISSUE TITLE
Add option to provide own SharedQueue for Bio-Formats Opener

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-image-loaders#11]
@NicoKiaru 

Could you please add an option to provide an own `SharedQueue` in `OpenerSettings`?

To be used with `OpenersToSpimData.getSpimData( openerSettings )`

**Comment by NicoKiaru** [comment]
Is it ok as well if I allow you to set the cache directly in the image loader ?

https://github.com/BIOP/bigdataviewer-image-loaders/blob/ce90dde18968e6762253850e8914f08cc5d63195/src/main/java/ch/epfl/biop/bdv/img/OpenersImageLoader.java#L212-L214

And put a setCache method ?

**Comment by NicoKiaru** [comment]
The cache is built easily from the shared queue:

https://github.com/BIOP/bigdataviewer-image-loaders/blob/ce90dde18968e6762253850e8914f08cc5d63195/src/main/java/ch/epfl/biop/bdv/img/OpenersImageLoader.java#L142

It's the only place where it is used in teh image loader

**Comment by tischi** [comment]
ok, then that should work for me!

**Comment by NicoKiaru** [comment]
fyi I'm replacing the cache of many image loaders in bdv-playground when I register an 'abstractspimdata':

https://github.com/bigdataviewer/bigdataviewer-playground/blob/9e98911174ae9c9369c8131a9c869e8a488fdc08/src/main/java/sc/fiji/bdvpg/scijava/services/SourceAndConverterService.java#L510

This is to solve memory issues, but it should solve threading issues as well: a single cache with a single queue is shared

**Comment by NicoKiaru** [comment]
See https://github.com/BIOP/bigdataviewer-image-loaders/issues/13
