### ISSUE TITLE
SharedQueue for ImagePlusToSpimData

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-image-loaders#13]
@NicoKiaru 

Would it be possible to add a `SharedQueue` (for a global volatile cache) to `ImagePlusToSpimData.getSpimData( imagePlus )`?

If one would open the ImagePlus as a VirtualStack, e.g. using `(new Opener()).openTiff()` then this could be another way of dealing with  [this issue](https://github.com/BIOP/bigdataviewer-image-loaders/issues/12) at least for TIFF files.

**Comment by tischi** [comment]
It would bypass Bio-Formats.

**Comment by NicoKiaru** [comment]
Same remark as https://github.com/BIOP/bigdataviewer-image-loaders/issues/11 : is it ok if I allow you to set the cache instead ?

**Comment by NicoKiaru** [comment]
Done here: https://github.com/BIOP/bigdataviewer-image-loaders/commit/56b385d2be743c28ed4d2cd776625a244b6b8798
