### ISSUE TITLE
More attributes in spimdata (HCS?)

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/bigdataviewer-image-loaders#16]
See discussion in https://github.com/mobie/mobie-viewer-fiji/issues/1007

**Comment by NicoKiaru** [comment]
The attributes for bio-formats are added here:

https://github.com/BIOP/bigdataviewer-image-loaders/blob/3d57189d6193d701ac401c3618503a92372187f9/src/main/java/ch/epfl/biop/bdv/img/bioformats/BioFormatsOpener.java#L257-L261

You can actually retrieve the bioformats series index from a dataset. Maybe that's enough ?

**Comment by NicoKiaru** [comment]
Linked forum thread: https://forum.image.sc/t/loading-hcs-plates-via-index-xml-with-bio-formats/79932/7

**Comment by tischi** [comment]
The thing is that I am parsing the XML myself and thus I need a robust way of mapping the images in the XML to the SpimData Setups.

The reason that I am parsing the XML is that I did not know that you had code for this already. For instance I am currently reading those fields:

```
      <PositionX Unit="m">0</PositionX>
      <PositionY Unit="m">0</PositionY>
      <PositionZ Unit="m">4E-06</PositionZ>
```

to put the images at the correct position. If that information also is available in the SpimData then I may not need to touch the XML myself at all. 

In any case, adding the ` <id>0101K1F1P1R1</id>` field from the XML to the SpimData attributes seems like a good idea. Would that readily possible?

**Comment by NicoKiaru** [comment]
Regarding what to put inside as extra metadata, I wouldn't put the 'id' but I'd rather like to add whatever is available in the public bio-formats API. What woudl you need the id ? Don't you need to column and row and plate number instead ?

**Comment by tischi** [comment]
Hi @NicoKiaru, I think you are right! If everything that is needed to construct the plate is in the SpimData then I would not need to touch the XML myself at all; which would be the best. 

What I need in the end is to populate this map:

`private HashMap< Channel, Map< Well, Set< Site > > > channelWellSites;`

and to instantiate the `Site`, which actually holds the image data, I would need to know the corresponding `setupId` within the `SpimData` object, which I think I woud get from your library and that would contain all data for the whole plate, right? Sorry, this is now quite a while ago and I do not remember all the details (even looking at my code...).

**Comment by NicoKiaru** [comment]
You have a set of Site for the different FOVs within the well ?

**Comment by tischi** [comment]
Yes, aka "Fields" or "Positions".

**Comment by NicoKiaru** [comment]
Done here: https://github.com/BIOP/bigdataviewer-image-loaders/commit/e66f0c84d1759faf1ee0c3a1d2538778ac4e7db7

@tischi when would you be able to test the current SNAPSHOT ?

**Comment by NicoKiaru** [comment]
Version 0.8.0 contain the changes:

https://maven.scijava.org/#nexus-search;quick~bigdataviewer%20image%20loader

**Comment by tischi** [comment]
Thanks a lot @NicoKiaru!

I am not sure when I will get around testing this, because I do not have a user right now anymore requesting this....this was "hot" one year ago...

**Comment by NicoKiaru** [comment]
Ahaha, sure, but then I release and we will see if there's an issue if somebody uses it.
