### ISSUE TITLE
Can one open data that is stored on S3?

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-image-loaders#20]
@NicoKiaru a quick glance at your code showed that you can handle URLs, but would that also work for objects stored on S3?

**Comment by NicoKiaru** [comment]
Nope, I was relying on you for that :-) (mobie-io, right ?).

The URL are handled in this repo through the Omero Ice API, so it's not going to work with a 'general' http request.

Maybe there's some basic http support with bio-formats directly, but I don't think it's clever and streams data, it rather downloads everything, and then display it.

**Comment by tischi** [comment]
Well, for anything BF related mobie-io is actually relying on this repo ;-)

I will then close this and we can follow up here: https://imagesc.zulipchat.com/#narrow/stream/393523-Java/topic/Open.20From.20S3.20using.20BioFormats
