### ISSUE TITLE
open multi-resolution TIFF

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-image-loaders#21]
Hi,

I think this is supposed to be a multi-resolution TIFF file.

[B3-1-C2.tif.zip](https://github.com/BIOP/bigdataviewer-image-loaders/files/13674950/B3-1-C2.tif.zip)

When I tried with your library here I think it opened it instead with a number of `ViewSetups`; I would expect just one multi-resolution setup instead?

<img width="773" alt="image" src="https://github.com/BIOP/bigdataviewer-image-loaders/assets/2157566/2376706d-fd64-4926-b468-0f346f667da5">

Could you have a look at that?

**Comment by NicoKiaru** [comment]
I can't open anything currently :-<

https://forum.image.sc/t/release-of-bio-formats-7-1-0/89725

Am I the only one ? I need to understand what's wrong.

**Comment by NicoKiaru** [comment]
Ok, I managed to fix my issue with tiffs (https://forum.image.sc/t/java-lang-nosuchfielderror-disablechromasubsampling-with-ptbiop-update-site/90061).

That was painful.

With regards to your file:

- It's probably multiresolution, but it's not ome-tiff multiresolution. Thus it's not recognised by bio-formats as multi resolution. There's nothing to be done at the level of this repository - it's something that needs to be dealt with at the bio-formats level.

**Comment by NicoKiaru** [comment]
Yep, so sorry, but it won't be worked on in this repo. Either you make an a bdv image loader for these data, or an ImageReader at the bio-formats level, or you manage to make the bf tiffreader to recognize the multiresolution of this tiff.
