### ISSUE TITLE
open time points from multiple files

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-image-loaders#22]
I have a situation where each time point is saved to an individual file; do you have code in this repo that would let me create **_one_** `SpimData` object from such data?

**Comment by NicoKiaru** [comment]
Not in this repo...

Things I'd look at:

* a rather complex way to reorder viewsetups from one imageloader into another imageloader:
https://github.com/BIOP/bigdataviewer-biop-tools/tree/master/src/main/java/ch/epfl/biop/spimdata/reordered

* the image loader from bigstitcher which is rather modular:
https://github.com/PreibischLab/multiview-reconstruction/blob/master/src/main/java/net/preibisch/mvrecon/fiji/spimdata/imgloaders/filemap2/FileMapImgLoaderLOCI2.java
