### ISSUE TITLE
VSI fix for BioFormats don't implemented yet

### ISSUE THREAD

**Issue by Rdornier** [BIOP/bigdataviewer-image-loaders#4]
VSI issue (see https://forum.image.sc/t/qupath-omero-weird-pyramid-levels/65484) is not fixed in the current implementation (See `BioFormatsSetupLoader` class.)

The piece of code fixing this issue is commented because of the `opener.getReaderFormat()` method that is BioFormats specific and cannot be added to the `Opener` interface. We need to find a compatible way to retrieve reader's format.

**Comment by NicoKiaru** [comment]
I duplicated @Rdornier 's code in https://github.com/BIOP/bigdataviewer-image-loaders/commit/53ebfb1214854cbf6b6da79c16da6abdd0b54c04 and put in the commit https://github.com/BIOP/bigdataviewer-image-loaders/commit/4a13ccc5986d173e38357c887c6c5877974e437a
