### ISSUE TITLE
Improve code performance

### ISSUE THREAD

**Issue by Rdornier** [BIOP/bigdataviewer-image-loaders#5]
Test the code and find a way to reduce the number of opened readers to be faster when reading and opening images. Specifically, the number of readers for BioFormats can be reduced to have one reader per file (and not one reader per serie).

**Comment by NicoKiaru** [comment]
Done with caching of objects in the opener, started in https://github.com/BIOP/bigdataviewer-image-loaders/commit/dd8819695f64f7e054f52438490d73ce86559a87
