### ISSUE TITLE
Wrong color for TIFF stacks?

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-image-loaders#8]
@NicoKiaru 

I have a TIFF stack that, when opening with ImageJ has a Gray LUT.

https://oc.embl.de/index.php/s/c0PH3iHDzsKZoUY

But when I create a SpimData object like this:

```
private AbstractSpimData< ? > openWithBioFormats( String path)
    {
        final File file = new File( path );
        List< OpenerSettings > openerSettings = new ArrayList<>();
        int numSeries = BioFormatsHelper.getNSeries(file);
        for (int i = 0; i < numSeries; i++) {
            openerSettings.add(
                    OpenerSettings.BioFormats()
                            .location(file)
                            .setSerie(i) );
        }

        return OpenersToSpimData.getSpimData( openerSettings );
    }
```

It claims that the color should be red `255-0-0-255` using:

```
final Displaysettings displaysettings = spimData.getSequenceDescription().getViewSetupsOrdered().get( imageIndex ).getAttribute( Displaysettings.class );
```

Do you have some idea would could be the issue?

**Comment by NicoKiaru** [comment]
Have you tried opening it with Bio-Formats in Fiji ? How does it look ?

**Comment by tischi** [comment]
> There are some mismatch between the imagej color and the bioformats found color, and I do not know where it comes from

@joshmoore do you have any insights into this?

**Comment by joshmoore** [comment]
Not off-hand, no.

**Comment by tischi** [comment]
> Not off-hand, no.

And "on-hand" ;-)
Is there someone at OME that we could ping about this?
Feels like a relevant bug that could be fixed?!
@joshmoore should I raise an issue somewhere?

**Comment by joshmoore** [comment]
Either an issue on https://github.com/ome/bioformats or a thread under https://forum.image.sc/tag/bio-formats would be appreciated.

**Comment by NicoKiaru** [comment]
@tischi You probably need to ping Wayne as well. The tiff ImageJ logic can be very ImageJ centric. Also, ImageJ supports the saving of LUT (Red/Green), and I'm not sure Bio-Formats allows this in the same way.

When there's no bio-formats channel color info, I suspect Bio-Formats makes has a default color sequence (like Red Green Blue Gray...)

**Comment by tischi** [comment]
https://forum.image.sc/t/bio-formats-color-wrong-for-imagej-images/76021

**Comment by tischi** [comment]
@NicoKiaru could you expose the `ColorMode` here (and/or set it to `Default`, which seems to work...)?

```
  OpenerSettings.BioFormats()
                            .location(file)
                            .setSerie(i) );
```

@dgault does the BioFormats Java API expose the `ColorMode` (as discussed in the Forum)?

**Comment by NicoKiaru** [comment]
The logic for setting the color (initially) is there:

https://github.com/BIOP/bigdataviewer-image-loaders/blob/6b780cce58fff5a6a386893ad18812bc6a77bbbc/src/main/java/ch/epfl/biop/bdv/img/opener/ChannelProperties.java#L173-L200

**Comment by tischi** [comment]
@dgault could you give us some advice how to modify that code that it resembles the "Default" mode of Bio-Formats?

**Comment by imagejan** [comment]
@tischi @NicoKiaru does this help?

https://github.com/ome/bioformats/blob/25645389e076a7bd0011e04c4dd8982c0f0614ed/components/bio-formats-plugins/src/loci/plugins/in/Colorizer.java#L114-L139

**Comment by NicoKiaru** [comment]
Thanks for the link @imagejan !

@tischi I'm not exactly sure which branch is executed in the Colorizer. If you can pin down what's occuring in Bio-Formats default mode and what's occuring in this library, I can try to implement it. For now it's a bit too fuzzy for me. If you manage to do it you can also file a PR.

**Comment by NicoKiaru** [comment]
Closing - this needs to be handled at the bio-formats level.
