### ISSUE TITLE
ImageName [0]

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-image-loaders#9]
@NicoKiaru I see some `ImageName [0]` log messages running MoBIE. I am not sure they where the come from. Could it be from this library?

**Comment by NicoKiaru** [comment]
Hum, yes probably, I'm in the middle of a big update, still not finalized. I suspect you are using a 'wip' dependency. Which version of bigdataviewer-image-loaders are you using ?

**Comment by tischi** [comment]
It is not so critical, maybe just do `Crtl + F` in your current code for `"ImageName` and if  you find it consider removing the output.

**Comment by NicoKiaru** [comment]
Done in https://github.com/BIOP/bigdataviewer-image-loaders/commit/0c3502ebd5fb07f3519989dde61c61c7ff3598eb
